### ISSUE TITLE
Upgrade to hasura-cli@1.0.0-beta.10

### ISSUE THREAD

**Issue by treyhuffine** [jjangga0214/hasura-cli#16]
A new version of the Hasura CLI was created, so just making it aware here :)

**Comment by jjangga0214** [comment]
@treyhuffine Thank you! 
I've been and will do regularly checking new versions, but notifications are always welcome :)

By the way, if you want, you can fix the version, and make a PR. 

https://github.com/jjangga0214/hasura-cli/blob/f726528cc37e0eea8a5e2349601c8bbe4339d30b/package.json#L3

That will be tested on CI, the result could help me publish rapidly!

**Comment by treyhuffine** [comment]
Thanks for the quick @jjangga0214! I'll be sure to submit a PR next time if I notice it :)
