### ISSUE TITLE
cannot create migrate instance: invalid character 'p' after top-level value 

### ISSUE THREAD

**Issue by jolyjf** [jjangga0214/hasura-cli#18]
## Versions
hasura-cli: 1.0.0-rc.1
Node: v10.15.2
npm: 6.13.4
## Command
Both:
`../../node_modules/.bin/hasura migrate status` and
`../../node_modules/.bin/hasura migrate apply`
...result in the same error.

### Directory from where the command is run
~/workspaces/claimsapp/dbutils/hasura/
### Hasura Migration Directory and Content
~/workspaces/claimsapp/dbutils/hasura/config.yaml
~/workspaces/claimsapp/dbutils/hasura/migrations/1576175828504_init/up.sql
~/workspaces/claimsapp/dbutils/hasura/migrations/1576175828504_init/up.yaml
### Directory of node_modules
~/workspaces/claimsapp/node_modules/

## Result
FATA[0000] cannot create migrate instance: invalid character 'p' after top-level value 
## Comments
- I'm not sure if it's related but the hasura instance I'm connecting to is using a self-signed certificate and in order to make the connection work I had put a copy of the certificate under `/etc/ssl/certs`, otherwise Hasura would complain.

- Migration 1576175828504_init was performed with a different certificate than the one I'm using to restore the database/metadata.

**Comment by jjangga0214** [comment]
@jolyjf Hi!
I guess this kind of issue occurs when the endpoint given to the cli is wrong, mostly.

Would you check the endpoint again for making it sure? 
(like, `--endpoint` or  `config.yaml`)

For example, it should not contain subdirectory URI paths. 
So, `http://localhost:8080` or `https://localhost:8080` are valid,
but `http://localhost:8080/v1/graphql` is not.

**Comment by jolyjf** [comment]
Hi @jjangga0214 !

Thanks for getting back to me.

I can confirm the endpoint is the same as when I originally (and successfully) created the migration in the first place.

My feeling -- and because it's the only thing that really changed since -- is that it's related to the certificate of the endpoint. Originally, I had a valid certificate for my endpoint, but now I'm using a staging certificate from _Let's Encrypt_. Since staging certificates are not trusted, _hasura-cli_ would complain like this:

`FATA[0000] version check: failed to get version from server: failed making version api call: Get https://mydomain.com/v1/version: x509: certificate signed by unknown authority`

To fix this, I take a copy of the certificate and copy it to `/etc/ssl/certs`. But it's at this point that the original error message comes up.

This weekend I will try with a non-staging certificate (I can't right now as I have reached the Let's Encrypt Limit) and I will be able to tell if this is the cause or not.

**Comment by jolyjf** [comment]
Still getting the same error even though my endpoint now has a valid certificate. I'll keep digging.

**Comment by jolyjf** [comment]
Got it working. I don't believe it was a problem with hasura-cli itself, but mostly my own wrong doing. :)

**Comment by hyperxpizza** [comment]
@jolyjf how did you get it working?
