### ISSUE TITLE
Release 1.1.0-beta.1

### ISSUE THREAD

**Issue by lukaspili** [jjangga0214/hasura-cli#20]

**Comment by shahidhk** [comment]
@jjangga0214 We'll be releasing beta updates from now on before the stable release. What is the convention that npm packages follow? Add a beta channel so that users can install it like `npm i hasura-cli@beta`?

**Comment by jjangga0214** [comment]
@shahidhk 
Thank you for clarify the releasing policy. Yes, there's npm `tag`, which is different from `version`. I published [description](https://github.com/jjangga0214/hasura-cli#installation) on README.

![Screenshot from 2020-01-17 01-42-56](https://user-images.githubusercontent.com/28584151/72544450-ba65bb80-38ca-11ea-835b-409470641bf0.png)

```bash
# Currently this will install `v1.1.0-beta.2`.
npm install hasura-cli@beta
```

```bash
# Currently this will install `v1.0.0`.
npm install hasura-cli@latest
```

```bash
# Currently this will install `v1.1.0-beta.2`.
npm install hasura-cli
```

**Comment by jjangga0214** [comment]
@lukaspili Thanks for making an issue! `v1.1.0-beta.1` and `v1.1.0-beta.2` are published :)
