### ISSUE TITLE
Upgrade to 1.2.0

### ISSUE THREAD

**Issue by jgoux** [jjangga0214/hasura-cli#29]
Hello,

The version 1.2.0 is now available and stable. :)

Is it possible to upgrade hasura-cli on npm?

Thanks!

**Comment by treyhuffine** [comment]
Submitted a PR - https://github.com/jjangga0214/hasura-cli/pull/30

**Comment by jjangga0214** [comment]
It's published. Thanks a lot to let me know!

**Comment by bloudermilk** [comment]
For some reason I'm not seeing the latest on NPM?

https://www.npmjs.com/package/hasura-cli

**Comment by treyhuffine** [comment]
It looks like the "publish" step was skipped in the workflow - https://github.com/jjangga0214/hasura-cli/runs/632520869

**Comment by jjangga0214** [comment]
@bloudermilk @treyhuffine You're right. 
I configured CI to publish the package only if it founds a git release tag on the latest commit. 
But I added a new commit after the release commit with git tag, then pushed it, which made the CI not think it should publish.    
This time I manually published it, haha :)
Thanks for comments!

**Comment by treyhuffine** [comment]
@jjangga0214 it looks like version 1.2.0 is still not showing up in NPM for some reason.

Also thanks for being so responsive with this, I'm a huge fan of this package and how helpful it is to work with Hasura :)

**Comment by jjangga0214** [comment]
@treyhuffine Happy to hear the package becomes helpful!

I can find it on npmjs.com and install it.

![Screenshot from 2020-04-30 21-23-44](https://user-images.githubusercontent.com/28584151/80710159-5f7a6c00-8b29-11ea-8f0e-b1819bba8767.png)

Maybe.. some of outdated cache is causing the problem?

**Comment by treyhuffine** [comment]
Thanks @jjangga0214 I'm seeing it as well now! It must have been a cache issue.
