### ISSUE TITLE
Error when running hasura metadata export

### ISSUE THREAD

**Issue by greatwitenorth** [jjangga0214/hasura-cli#34]
When running `hasura metadata export` I see the following error:

```
DEBU global config file exisits, verifying contents
DEBU global config is pre-set to &cli.GlobalConfig{UUID:"74db6a30-fe5b-47b4-bc71-bb6f9b816a21", EnableTelemetry:true, ShowUpdateNotification:true, CLIEnvironment:""}
DEBU global config: uuid: 74db6a30-fe5b-47b4-bc71-bb6f9b816a21
DEBU global config: enableTelemetry: true
DEBU global config: showUpdateNotification: true
DEBU global config: cliEnvironment:
DEBU telemetry: beaming payload failed: [Post https://telemetry.hasura.io/v1/http: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
FATA[0012] ensuring plugins index failed: Get https://github.com/hasura/cli-plugins-index.git/info/refs?service=git-upload-pack: net/http: TLS handshake timeout
```

I've updated to the most recent version of hasura-cli:
```
INFO hasura cli                                    version=v1.2.2
```

**Comment by jjangga0214** [comment]
@greatwitenorth Hi, thank you for reporting the issue :)

`hasura-cli` wraps [the official CLI binary](https://github.com/hasura/graphql-engine/releases/tag/v1.2.2). So, in general, most issues are actually from the CLI binary itself, not `hasura-cli`. In that case, you should forward this issue to [hasura/graphql-engine](https://github.com/hasura/graphql-engine).

If you still suspect `hasura-cli`, I'd like to ask some questions.

1. Is `hasura metadata export` the only command that makes an error?

2. Would you execute same commands (including, but not limited to `hasura metadata export`) against `hasura-cli` and _"the official CLI binary"_? Is there a difference?

**Comment by jjangga0214** [comment]
I close this as I guess it's not an issue of `hasura-cli` and there's no response.
