### ISSUE TITLE
Metadata apply failed on 1.3.3

### ISSUE THREAD

**Issue by gainsboroughtech** [jjangga0214/hasura-cli#55]
On v1.3.3, ran `hasura metadata apply --admin-secret="...."`

Error:

FATA[0001] failed to apply metadata: cannot apply metadata on the database: cannot build actions from metadata: cannot fetch plugin manfiest cli-ext: plugin version is not available 

Rolled back to 1.3.2, metadata applied successfully

**Comment by jjangga0214** [comment]
Hi, @gainsboroughtech.

Thanks for reporting the issue. 

However, I think it should be posted to [hasura/graphql-engine](hasura/graphql-engine).

If you have any questions or information to share, please do so anytime.

If there's no response, I will close this issue for a few days later.

Thanks.
