### ISSUE TITLE
New release after security update

### ISSUE THREAD

**Issue by elitan** [jjangga0214/hasura-cli#58]
A new release must happen after the last security update of axios (https://github.com/jjangga0214/hasura-cli/commit/807a792679f175884945c2c73d8f2cf5a10a4bb2).

**Comment by jjangga0214** [comment]
@elitan Thanks for the notification! 
The PR 807a792 is merged by 07bfbfa881fa138b949505929f464f622bda6822. 
Thus, any new release will have that update.
