### ISSUE TITLE
clear error message

### ISSUE THREAD

**Issue by dlinah** [jjangga0214/hasura-cli#62]
hi, i have struggle a bit with `hasura metadata apply` error message , if there is an inconsistency between the data and metadata  , the cli just say there is an inconsistency and throw back the whole file (which is 3000 lines) , it cost me a couple of hours (befor checking the server errors) , and then randomly i saw that the hasura console  display the metadata error nicely.
maybe a quick fix would be add the hasura metadata error page as link in the response or return those same errors in the `hasura metadata apply` response

**Comment by jjangga0214** [comment]
Hi, @dlinah !

Thanks for reporting the issue.

However, I guess it's an issue of hasura-cli binary, which should be posted on [hasura/graphql-engine](https://github.com/hasura/graphql-engine).

If you don't agree. or have any questions or information to share, please do so freely.

If there's no response, I will close this issue for a few days later.

Thanks.
