### ISSUE TITLE
New Hasura release

### ISSUE THREAD

**Issue by jgoux** [jjangga0214/hasura-cli#73]
Hello,

There are 3 new hasura releases since the last one published by `hasura-cli` : 

- v2.1.0-beta.2
- v2.0.10
- v2.1.0-beta.1

Would it be possible to publish those?

Thanks a lot!

**Comment by jjangga0214** [comment]
Hi!

Thanks for the issue.
I've just published them all.
Sometimes I miss publishing, and sorry for the inconvenience.
Thanks!
