### ISSUE TITLE
Version 2.3.0 is missing

### ISSUE THREAD

**Issue by sasial-dev** [jjangga0214/hasura-cli#79]
Unable to install v2.3.0 of the hasura CLI

**Comment by jjangga0214** [comment]
Thanks for reporting! 
And also sorry for being late!

It's just published!

Thank you!

**Comment by zenflow** [comment]
@jjangga0214 please be sure to tag the release in Git when you make a release. Latest releases don't appear on GitHub but they do on NPM.

**Comment by jjangga0214** [comment]
@zenflow You're right. Thanks for the advice :)
