### ISSUE TITLE
  9907 segmentation fault  hasura console --endpoint http://localhost:8080

### ISSUE THREAD

**Issue by sranvare07** [jjangga0214/hasura-cli#92]
Getting the above error message on Mac M1 after upgrading to MacOs Ventura.

**Comment by jjangga0214** [comment]
@sranvare07 Hi!
Have you reported this symptom to Hasura's repo as well?

**Comment by sranvare07** [comment]
@jjangga0214Hey, haven't reported with since Hasura is working fine having issues only with hasura-cli.

**Comment by jjangga0214** [comment]
@sranvare07 So I am curious if the case is which of these.
1. The official hasura-cli executable binary works fine, but this npm package(this repo's project) doesn't.
2. Both of them don't work.
Thanks for the reporting anyway :)

**Comment by jjangga0214** [comment]
Feel free to reopen the issue if you want!
