### ISSUE TITLE
Hasura has deleted vulnerable releases

### ISSUE THREAD

**Issue by kamsar** [jjangga0214/hasura-cli#99]
Hasura has recently deleted vulnerable releases (i.e. 2.15.1) from their GitHub where this package downloads them. This has broken the package for all its currently released versions later than 2.9.0, as the binaries are now 404s.

**Comment by jjangga0214** [comment]
Hi!
I've deprecated all the vulnerable versions.
When downloading, a warning message to guide people to upgrade to the proper versions would appear.
Thanks a lot for reporting!
